package edu.cmu.photogenome.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Importedmetadata generated by hbm2java
 */
@Entity
@Table(name = "importedmetadata", catalog = "pg_db")
public class ImportedMetadata implements java.io.Serializable {

	private Integer importedmetadataId;
	private int photoId;
	private String importedMetadata;

	public ImportedMetadata() {
	}

	public ImportedMetadata(int photoId, String importedMetadata) {
		this.photoId = photoId;
		this.importedMetadata = importedMetadata;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "importedmetadata_Id", unique = true, nullable = false)
	public Integer getImportedmetadataId() {
		return this.importedmetadataId;
	}

	public void setImportedmetadataId(Integer importedmetadataId) {
		this.importedmetadataId = importedmetadataId;
	}

	@Column(name = "photo_Id")
	public int getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(int photoId) {
		this.photoId = photoId;
	}

	@Column(name = "imported_MetaData", length = 65535)
	public String getImportedMetadata() {
		return this.importedMetadata;
	}

	public void setImportedMetadata(String importedMetadata) {
		this.importedMetadata = importedMetadata;
	}

}
