package edu.cmu.photogenome.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Photometadata generated by hbm2java
 */
@Entity
@Table(name = "photometadata", catalog = "PG_DB")
public class PhotoMetadata implements java.io.Serializable {

	private Integer photometadataId;
	private int photoId;
	private String photoMetadata;

	public PhotoMetadata() {
	}

	public PhotoMetadata(int photoId, String photoMetadata) {
		this.photoId = photoId;
		this.photoMetadata = photoMetadata;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "photometadata_Id", unique = true, nullable = false)
	public Integer getPhotometadataId() {
		return this.photometadataId;
	}

	public void setPhotometadataId(Integer photometadataId) {
		this.photometadataId = photometadataId;
	}

	@Column(name = "photo_Id")
	public int getPhotoId() {
		return this.photoId;
	}

	public void setPhoto(int photoId) {
		this.photoId = photoId;
	}

	@Column(name = "Photo_MetaData", length = 65535)
	public String getPhotoMetadata() {
		return this.photoMetadata;
	}

	public void setPhotoMetaData(String photoMetadata) {
		this.photoMetadata = photoMetadata;
	}

}
