package edu.cmu.photogenome.domain;

// Generated May 24, 2013 3:47:50 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name = "photo", catalog = "PG_DB")
public class Photo implements java.io.Serializable {

	private Integer photoId;
	private String photoName;
	private String photoDesc;
	private String photoLink;
	private String photoMetadatalink;
	private int userId;
	private Date photoTimestamp;
	private Boolean photoIsdeleted;
	private String photoOption1;
	private String photoOption2;
	private String photoOption3;
	private String photoOption4;
	private String photoOption5;

	public Photo() {
	}

	public Photo(int userId, Date photoTimestamp) {
		this.userId = userId;
		this.photoTimestamp = photoTimestamp;
	}

	public Photo(String photoName, String photoDesc, String photoLink,
			String photoMetadatalink, int userId, Date photoTimestamp,
			Boolean photoIsdeleted, String photoOption1, String photoOption2,
			String photoOption3, String photoOption4, String photoOption5) {
		this.photoName = photoName;
		this.photoDesc = photoDesc;
		this.photoLink = photoLink;
		this.photoMetadatalink = photoMetadatalink;
		this.userId = userId;
		this.photoTimestamp = photoTimestamp;
		this.photoIsdeleted = photoIsdeleted;
		this.photoOption1 = photoOption1;
		this.photoOption2 = photoOption2;
		this.photoOption3 = photoOption3;
		this.photoOption4 = photoOption4;
		this.photoOption5 = photoOption5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "photo_id", unique = true, nullable = false)
	public Integer getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(Integer photoId) {
		this.photoId = photoId;
	}

	@Column(name = "photo_name", length = 200)
	public String getPhotoName() {
		return this.photoName;
	}

	public void setPhotoName(String photoName) {
		this.photoName = photoName;
	}

	@Column(name = "photo_desc", length = 65535)
	public String getPhotoDesc() {
		return this.photoDesc;
	}

	public void setPhotoDesc(String photoDesc) {
		this.photoDesc = photoDesc;
	}

	@Column(name = "photo_link", length = 65535)
	public String getPhotoLink() {
		return this.photoLink;
	}

	public void setPhotoLink(String photoLink) {
		this.photoLink = photoLink;
	}

	@Column(name = "photo_metadatalink", length = 65535)
	public String getPhotoMetadatalink() {
		return this.photoMetadatalink;
	}

	public void setPhotoMetadatalink(String photoMetadatalink) {
		this.photoMetadatalink = photoMetadatalink;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "photo_timestamp", nullable = false, length = 19)
	public Date getPhotoTimestamp() {
		return this.photoTimestamp;
	}

	public void setPhotoTimestamp(Date photoTimestamp) {
		this.photoTimestamp = photoTimestamp;
	}

	@Column(name = "photo_isdeleted")
	public Boolean getPhotoIsdeleted() {
		return this.photoIsdeleted;
	}

	public void setPhotoIsdeleted(Boolean photoIsdeleted) {
		this.photoIsdeleted = photoIsdeleted;
	}

	@Column(name = "photo_option1", length = 65535)
	public String getPhotoOption1() {
		return this.photoOption1;
	}

	public void setPhotoOption1(String photoOption1) {
		this.photoOption1 = photoOption1;
	}

	@Column(name = "photo_option2", length = 65535)
	public String getPhotoOption2() {
		return this.photoOption2;
	}

	public void setPhotoOption2(String photoOption2) {
		this.photoOption2 = photoOption2;
	}

	@Column(name = "photo_option3", length = 65535)
	public String getPhotoOption3() {
		return this.photoOption3;
	}

	public void setPhotoOption3(String photoOption3) {
		this.photoOption3 = photoOption3;
	}

	@Column(name = "photo_option4", length = 65535)
	public String getPhotoOption4() {
		return this.photoOption4;
	}

	public void setPhotoOption4(String photoOption4) {
		this.photoOption4 = photoOption4;
	}

	@Column(name = "photo_option5", length = 65535)
	public String getPhotoOption5() {
		return this.photoOption5;
	}

	public void setPhotoOption5(String photoOption5) {
		this.photoOption5 = photoOption5;
	}

}
