package edu.cmu.photogenome.domain;

// Generated May 24, 2013 3:47:50 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Regioncomment generated by hbm2java
 */
@Entity
@Table(name = "regioncomment")
public class RegionComment implements java.io.Serializable {

	private Integer regionCommentId;
	private String regionCommentText;
	private int photoId;
	private int regionId;
	private int userId;
	private Date regionCommentTimestamp;
	private Boolean regionCommentIsdeleted;
	private String regionCommentOption1;
	private String regionCommentOption2;
	private String regionCommentOption3;
	private String regionCommentOption4;
	private String regionCommentOption5;

	public RegionComment() {
	}

	public RegionComment(int photoId, int regionId, int userId,
			Date regionCommentTimestamp) {
		this.photoId = photoId;
		this.regionId = regionId;
		this.userId = userId;
		this.regionCommentTimestamp = regionCommentTimestamp;
	}

	public RegionComment(String regionCommentText, int photoId, int regionId,
			int userId, Date regionCommentTimestamp,
			Boolean regionCommentIsdeleted, String regionCommentOption1,
			String regionCommentOption2, String regionCommentOption3,
			String regionCommentOption4, String regionCommentOption5) {
		this.regionCommentText = regionCommentText;
		this.photoId = photoId;
		this.regionId = regionId;
		this.userId = userId;
		this.regionCommentTimestamp = regionCommentTimestamp;
		this.regionCommentIsdeleted = regionCommentIsdeleted;
		this.regionCommentOption1 = regionCommentOption1;
		this.regionCommentOption2 = regionCommentOption2;
		this.regionCommentOption3 = regionCommentOption3;
		this.regionCommentOption4 = regionCommentOption4;
		this.regionCommentOption5 = regionCommentOption5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "regionComment_id", unique = true, nullable = false)
	public Integer getRegionCommentId() {
		return this.regionCommentId;
	}

	public void setRegionCommentId(Integer regionCommentId) {
		this.regionCommentId = regionCommentId;
	}

	@Column(name = "regionComment_text", length = 65535)
	public String getRegionCommentText() {
		return this.regionCommentText;
	}

	public void setRegionCommentText(String regionCommentText) {
		this.regionCommentText = regionCommentText;
	}

	@Column(name = "photo_id", nullable = false)
	public int getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(int photoId) {
		this.photoId = photoId;
	}

	@Column(name = "region_id", nullable = false)
	public int getRegionId() {
		return this.regionId;
	}

	public void setRegionId(int regionId) {
		this.regionId = regionId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegionComment_timestamp", nullable = false, length = 19)
	public Date getRegionCommentTimestamp() {
		return this.regionCommentTimestamp;
	}

	public void setRegionCommentTimestamp(Date regionCommentTimestamp) {
		this.regionCommentTimestamp = regionCommentTimestamp;
	}

	@Column(name = "RegionComment_isdeleted")
	public Boolean getRegionCommentIsdeleted() {
		return this.regionCommentIsdeleted;
	}

	public void setRegionCommentIsdeleted(Boolean regionCommentIsdeleted) {
		this.regionCommentIsdeleted = regionCommentIsdeleted;
	}

	@Column(name = "RegionComment_option1", length = 65535)
	public String getRegionCommentOption1() {
		return this.regionCommentOption1;
	}

	public void setRegionCommentOption1(String regionCommentOption1) {
		this.regionCommentOption1 = regionCommentOption1;
	}

	@Column(name = "RegionComment_option2", length = 65535)
	public String getRegionCommentOption2() {
		return this.regionCommentOption2;
	}

	public void setRegionCommentOption2(String regionCommentOption2) {
		this.regionCommentOption2 = regionCommentOption2;
	}

	@Column(name = "RegionComment_option3", length = 65535)
	public String getRegionCommentOption3() {
		return this.regionCommentOption3;
	}

	public void setRegionCommentOption3(String regionCommentOption3) {
		this.regionCommentOption3 = regionCommentOption3;
	}

	@Column(name = "RegionComment_option4", length = 65535)
	public String getRegionCommentOption4() {
		return this.regionCommentOption4;
	}

	public void setRegionCommentOption4(String regionCommentOption4) {
		this.regionCommentOption4 = regionCommentOption4;
	}

	@Column(name = "RegionComment_option5", length = 65535)
	public String getRegionCommentOption5() {
		return this.regionCommentOption5;
	}

	public void setRegionCommentOption5(String regionCommentOption5) {
		this.regionCommentOption5 = regionCommentOption5;
	}

}
