package edu.cmu.photogenome.domain;

// Generated May 24, 2013 3:47:50 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role")
public class Role implements java.io.Serializable {

	private Integer roleId;
	private String roleName;
	private Date roleTimestamp;
	private Boolean roleIsdeleted;
	private String roleOption1;
	private String roleOption2;
	private String roleOption3;
	private String roleOption4;
	private String roleOption5;

	public Role() {
	}

	public Role(Date roleTimestamp) {
		this.roleTimestamp = roleTimestamp;
	}

	public Role(String roleName, Date roleTimestamp, Boolean roleIsdeleted,
			String roleOption1, String roleOption2, String roleOption3,
			String roleOption4, String roleOption5) {
		this.roleName = roleName;
		this.roleTimestamp = roleTimestamp;
		this.roleIsdeleted = roleIsdeleted;
		this.roleOption1 = roleOption1;
		this.roleOption2 = roleOption2;
		this.roleOption3 = roleOption3;
		this.roleOption4 = roleOption4;
		this.roleOption5 = roleOption5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", length = 100)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "role_timestamp", nullable = false, length = 19)
	public Date getRoleTimestamp() {
		return this.roleTimestamp;
	}

	public void setRoleTimestamp(Date roleTimestamp) {
		this.roleTimestamp = roleTimestamp;
	}

	@Column(name = "role_isdeleted")
	public Boolean getRoleIsdeleted() {
		return this.roleIsdeleted;
	}

	public void setRoleIsdeleted(Boolean roleIsdeleted) {
		this.roleIsdeleted = roleIsdeleted;
	}

	@Column(name = "role_option1", length = 65535)
	public String getRoleOption1() {
		return this.roleOption1;
	}

	public void setRoleOption1(String roleOption1) {
		this.roleOption1 = roleOption1;
	}

	@Column(name = "role_option2", length = 65535)
	public String getRoleOption2() {
		return this.roleOption2;
	}

	public void setRoleOption2(String roleOption2) {
		this.roleOption2 = roleOption2;
	}

	@Column(name = "role_option3", length = 65535)
	public String getRoleOption3() {
		return this.roleOption3;
	}

	public void setRoleOption3(String roleOption3) {
		this.roleOption3 = roleOption3;
	}

	@Column(name = "role_option4", length = 65535)
	public String getRoleOption4() {
		return this.roleOption4;
	}

	public void setRoleOption4(String roleOption4) {
		this.roleOption4 = roleOption4;
	}

	@Column(name = "role_option5", length = 65535)
	public String getRoleOption5() {
		return this.roleOption5;
	}

	public void setRoleOption5(String roleOption5) {
		this.roleOption5 = roleOption5;
	}

}
