package edu.cmu.photogenome.domain;

// Generated May 24, 2013 3:47:50 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shape generated by hbm2java
 */
@Entity
@Table(name = "shape", catalog = "photogenomeDatabase")
public class Shape implements java.io.Serializable {

	private Integer shapeId;
	private String shapeName;
	private String shapeDesc;
	private String shapeLinetype;
	private Date shapeTimestamp;
	private Boolean shapeIsdeleted;
	private String shapeOption1;
	private String shapeOption2;
	private String shapeOption3;
	private String shapeOption4;
	private String shapeOption5;

	public Shape() {
	}

	public Shape(Date shapeTimestamp) {
		this.shapeTimestamp = shapeTimestamp;
	}

	public Shape(String shapeName, String shapeDesc, String shapeLinetype,
			Date shapeTimestamp, Boolean shapeIsdeleted, String shapeOption1,
			String shapeOption2, String shapeOption3, String shapeOption4,
			String shapeOption5) {
		this.shapeName = shapeName;
		this.shapeDesc = shapeDesc;
		this.shapeLinetype = shapeLinetype;
		this.shapeTimestamp = shapeTimestamp;
		this.shapeIsdeleted = shapeIsdeleted;
		this.shapeOption1 = shapeOption1;
		this.shapeOption2 = shapeOption2;
		this.shapeOption3 = shapeOption3;
		this.shapeOption4 = shapeOption4;
		this.shapeOption5 = shapeOption5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "shape_id", unique = true, nullable = false)
	public Integer getShapeId() {
		return this.shapeId;
	}

	public void setShapeId(Integer shapeId) {
		this.shapeId = shapeId;
	}

	@Column(name = "shape_name", length = 200)
	public String getShapeName() {
		return this.shapeName;
	}

	public void setShapeName(String shapeName) {
		this.shapeName = shapeName;
	}

	@Column(name = "shape_desc", length = 65535)
	public String getShapeDesc() {
		return this.shapeDesc;
	}

	public void setShapeDesc(String shapeDesc) {
		this.shapeDesc = shapeDesc;
	}

	@Column(name = "shape_linetype", length = 200)
	public String getShapeLinetype() {
		return this.shapeLinetype;
	}

	public void setShapeLinetype(String shapeLinetype) {
		this.shapeLinetype = shapeLinetype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shape_timestamp", nullable = false, length = 19)
	public Date getShapeTimestamp() {
		return this.shapeTimestamp;
	}

	public void setShapeTimestamp(Date shapeTimestamp) {
		this.shapeTimestamp = shapeTimestamp;
	}

	@Column(name = "shape_isdeleted")
	public Boolean getShapeIsdeleted() {
		return this.shapeIsdeleted;
	}

	public void setShapeIsdeleted(Boolean shapeIsdeleted) {
		this.shapeIsdeleted = shapeIsdeleted;
	}

	@Column(name = "shape_option1", length = 65535)
	public String getShapeOption1() {
		return this.shapeOption1;
	}

	public void setShapeOption1(String shapeOption1) {
		this.shapeOption1 = shapeOption1;
	}

	@Column(name = "shape_option2", length = 65535)
	public String getShapeOption2() {
		return this.shapeOption2;
	}

	public void setShapeOption2(String shapeOption2) {
		this.shapeOption2 = shapeOption2;
	}

	@Column(name = "shape_option3", length = 65535)
	public String getShapeOption3() {
		return this.shapeOption3;
	}

	public void setShapeOption3(String shapeOption3) {
		this.shapeOption3 = shapeOption3;
	}

	@Column(name = "shape_option4", length = 65535)
	public String getShapeOption4() {
		return this.shapeOption4;
	}

	public void setShapeOption4(String shapeOption4) {
		this.shapeOption4 = shapeOption4;
	}

	@Column(name = "shape_option5", length = 65535)
	public String getShapeOption5() {
		return this.shapeOption5;
	}

	public void setShapeOption5(String shapeOption5) {
		this.shapeOption5 = shapeOption5;
	}

}
