package edu.cmu.photogenome.domain;

// Generated May 21, 2013 11:45:28 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "PG_DB")
public class User implements java.io.Serializable {

	private Integer userId;
	private String userPassword;
	private Integer roleId;
	private String userFirstName;
	private String userMiddleName;
	private String userLastName;
	private String userEmailId;
	private Date userDateOfBirth;
	private String userAddress;
	private String userPhoneNum;
	private String userCountry;
	private String userState;
	private String userCity;
	private Date userTimestamp;
	private Boolean userIsdeleted;
	private String userOption1;
	private String userOption2;
	private String userOption3;
	private String userOption4;
	private String userOption5;

	public User() {
	}

	public User(Date userTimestamp) {
		this.userTimestamp = userTimestamp;
	}

	public User(String userPassword, Integer roleId, String userFirstName,
			String userMiddleName, String userLastName, String userEmailId,
			Date userDateOfBirth, String userAddress, String userPhoneNum,
			String userCountry, String userState, String userCity,
			Date userTimestamp, Boolean userIsdeleted, String userOption1,
			String userOption2, String userOption3, String userOption4,
			String userOption5) {
		this.userPassword = userPassword;
		this.roleId = roleId;
		this.userFirstName = userFirstName;
		this.userMiddleName = userMiddleName;
		this.userLastName = userLastName;
		this.userEmailId = userEmailId;
		this.userDateOfBirth = userDateOfBirth;
		this.userAddress = userAddress;
		this.userPhoneNum = userPhoneNum;
		this.userCountry = userCountry;
		this.userState = userState;
		this.userCity = userCity;
		this.userTimestamp = userTimestamp;
		this.userIsdeleted = userIsdeleted;
		this.userOption1 = userOption1;
		this.userOption2 = userOption2;
		this.userOption3 = userOption3;
		this.userOption4 = userOption4;
		this.userOption5 = userOption5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_password", length = 40)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "user_first_name", length = 100)
	public String getUserFirstName() {
		return this.userFirstName;
	}

	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	@Column(name = "user_middle_name", length = 100)
	public String getUserMiddleName() {
		return this.userMiddleName;
	}

	public void setUserMiddleName(String userMiddleName) {
		this.userMiddleName = userMiddleName;
	}

	@Column(name = "user_last_name", length = 100)
	public String getUserLastName() {
		return this.userLastName;
	}

	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}

	@Column(name = "user_email_id")
	public String getUserEmailId() {
		return this.userEmailId;
	}

	public void setUserEmailId(String userEmailId) {
		this.userEmailId = userEmailId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_date_of_birth", length = 19)
	public Date getUserDateOfBirth() {
		return this.userDateOfBirth;
	}

	public void setUserDateOfBirth(Date userDateOfBirth) {
		this.userDateOfBirth = userDateOfBirth;
	}

	@Column(name = "user_address", length = 65535)
	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	@Column(name = "user_phone_num", length = 100)
	public String getUserPhoneNum() {
		return this.userPhoneNum;
	}

	public void setUserPhoneNum(String userPhoneNum) {
		this.userPhoneNum = userPhoneNum;
	}

	@Column(name = "user_country", length = 100)
	public String getUserCountry() {
		return this.userCountry;
	}

	public void setUserCountry(String userCountry) {
		this.userCountry = userCountry;
	}

	@Column(name = "user_state", length = 100)
	public String getUserState() {
		return this.userState;
	}

	public void setUserState(String userState) {
		this.userState = userState;
	}

	@Column(name = "user_city", length = 100)
	public String getUserCity() {
		return this.userCity;
	}

	public void setUserCity(String userCity) {
		this.userCity = userCity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_timestamp", nullable = false, length = 19)
	public Date getUserTimestamp() {
		return this.userTimestamp;
	}

	public void setUserTimestamp(Date userTimestamp) {
		this.userTimestamp = userTimestamp;
	}

	@Column(name = "user_isdeleted")
	public Boolean getUserIsdeleted() {
		return this.userIsdeleted;
	}

	public void setUserIsdeleted(Boolean userIsdeleted) {
		this.userIsdeleted = userIsdeleted;
	}

	@Column(name = "user_option1", length = 65535)
	public String getUserOption1() {
		return this.userOption1;
	}

	public void setUserOption1(String userOption1) {
		this.userOption1 = userOption1;
	}

	@Column(name = "user_option2", length = 65535)
	public String getUserOption2() {
		return this.userOption2;
	}

	public void setUserOption2(String userOption2) {
		this.userOption2 = userOption2;
	}

	@Column(name = "user_option3", length = 65535)
	public String getUserOption3() {
		return this.userOption3;
	}

	public void setUserOption3(String userOption3) {
		this.userOption3 = userOption3;
	}

	@Column(name = "user_option4", length = 65535)
	public String getUserOption4() {
		return this.userOption4;
	}

	public void setUserOption4(String userOption4) {
		this.userOption4 = userOption4;
	}

	@Column(name = "user_option5", length = 65535)
	public String getUserOption5() {
		return this.userOption5;
	}

	public void setUserOption5(String userOption5) {
		this.userOption5 = userOption5;
	}

}
